# Generated by Django 3.2.5 on 2022-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('for_dept', models.CharField(max_length=255)),
                ('section', models.IntegerField()),
                ('Time_WeekDay', models.CharField(max_length=255)),
                ('Room', models.CharField(max_length=255)),
                ('available', models.IntegerField()),
                ('taken', models.IntegerField(default=0)),
                ('has_lab', models.BooleanField(default=False)),
                ('l_Time_WeekDay', models.CharField(blank=True, max_length=255, null=True)),
                ('l_Room', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('credit', models.FloatField()),
                ('min_credit_required', models.IntegerField(default=0)),
                ('prerequisite', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Semester',
            fields=[
                ('semester', models.CharField(max_length=100, primary_key=True)),
                ('credit_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.CharField(default=False, max_length=255)),
                ('course', models.CharField(default=False, max_length=255)),
                ('credit', models.FloatField(default=False)),
                ('section', models.IntegerField(default=False)),
                ('Time_WeekDay', models.CharField(default=False, max_length=255)),
                ('Room', models.CharField(default=False, max_length=255)),
                ('has_lab', models.BooleanField(default=False)),
                ('l_Time_WeekDay', models.CharField(blank=True, max_length=255, null=True)),
                ('l_Room', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_initial', models.CharField(default='TBA', max_length=255)),
            ],
        ),
    ]
