# Generated by Django 3.2.5 on 2022-03-19 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('advising', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='takecourse',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising.course'),
        ),
        migrations.AddField(
            model_name='assignedcourse',
            name='current_semester',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='advising.create_semester'),
        ),
        migrations.AddField(
            model_name='assignedcourse',
            name='faculty_initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
    ]
