# Generated by Django 3.2.5 on 2022-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
