# Generated by Django 3.2.5 on 2022-03-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0004_alter_assignedcourse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='for_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising.department'),
        ),
    ]
