# Generated by Django 4.0.2 on 2022-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0006_alter_create_semester_semester_dropsemesterrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_info', models.IntegerField()),
                ('semester', models.CharField(default=False, max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
