# Generated by Django 4.0.2 on 2022-04-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0007_dropstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='takecourse',
            name='withdraw_status',
            field=models.BooleanField(default=False),
        ),
    ]
