# Generated by Django 3.2.5 on 2022-03-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0002_initial'),
        ('home', '0002_alter_student_admitted_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted_Semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising.create_semester'),
        ),
    ]
