# Generated by Django 3.2.5 on 2022-03-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0002_initial'),
        ('home', '0004_alter_student_admitted_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='advising.department'),
        ),
    ]
